LICENSE
src/paratext-bible-text-collection/LICENSE
src/paratext-bible-word-list/LICENSE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/3)

Updated license year

---

src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/4)

Reworked useDialogCallback

---

package-lock.json
package.json
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-text-collection/webpack/webpack.config.base.ts
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json
src/paratext-bible-word-list/webpack/webpack.config.base.ts
webpack/webpack.config.base.ts

Basically just updated from templates
Resolves #594
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/6)

Deduped `@emotion/react`

---

.eslintrc.cjs
package-lock.json
package.json
src/paratext-bible-text-collection/.eslintrc.js
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-text-collection/src/web-views/components/chapter-view.component.tsx
src/paratext-bible-text-collection/src/web-views/editor-styles/_editor-overrides.scss
src/paratext-bible-word-list/.eslintrc.js
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/15)

Update extensions from templates - npm workspace, dts fix

---

package-lock.json
package.json
src/paratext-bible-text-collection/src/web-views/components/chapter-view.component.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/16)

update editor - no spell check

---

lib/git.util.ts
src/paratext-bible-text-collection/contributions/localizedStrings.json
src/paratext-bible-text-collection/manifest.json
src/paratext-bible-word-list/contributions/localizedStrings.json
src/paratext-bible-word-list/manifest.json
webpack/webpack.util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/17)

Added localized strings

---

src/paratext-bible-text-collection/src/main.ts
src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx
src/paratext-bible-word-list/src/main.ts
src/paratext-bible-word-list/src/word-list.web-view.tsx

Goes with https://github.com/paranext/paranext-core/issues/866
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/18)

Updated web view project id to use web view definition

---

src/paratext-bible-text-collection/src/util.ts
src/paratext-bible-text-collection/src/web-views/components/verse-display.component.tsx
src/paratext-bible-word-list/src/main.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/24)

Update USFM project data references to match new interfaces

---

package-lock.json
package.json
src/paratext-bible-word-list/src/word-content-viewer.component.tsx
src/paratext-bible-word-list/src/word-list.web-view.tsx
src/paratext-bible-word-list/src/word-table.component.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27)

Remove RefSelector and use new Table and DataTable

---

package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/33)

Run npm install after dependabot updates

---

package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-text-collection/src/web-views/components/chapter-view.component.tsx
src/paratext-bible-text-collection/src/web-views/components/verse-display.component.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/37)

Support RTL for OHEBGRK

---

src/paratext-bible-text-collection/src/web-views/editor-styles/_editor-overrides.scss
src/paratext-bible-text-collection/src/web-views/editor-styles/_editor.scss
src/paratext-bible-text-collection/src/web-views/editor-styles/_usj-nodes.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/38)

update SCSS after editor upgrade

---

CHANGELOG.md
package-lock.json
package.json
src/paratext-bible-text-collection/manifest.json
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-word-list/manifest.json
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/39)

Merge Release/v0.1.0 back to main

---

CHANGELOG.md
package-lock.json
package.json
src/paratext-bible-text-collection/manifest.json
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-word-list/manifest.json
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/40)

Merge Release/v0.1.1 back to main

---

package-lock.json

Trying to fix https://github.com/paranext/paratext-10-studio/actions/runs/11437431795/job/31848819276
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/44)

Regenerated package-lock.json by overwriting with file from template and running npm i

---

src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/webpack/webpack.config.base.ts
src/paratext-bible-text-collection/webpack/webpack.config.main.ts
src/paratext-bible-text-collection/webpack/webpack.config.web-view.ts
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/src/types/paratext-bible-word-list.d.ts
src/paratext-bible-word-list/src/word-list.web-view.tsx
src/paratext-bible-word-list/webpack/webpack.config.base.ts
src/paratext-bible-word-list/webpack/webpack.config.main.ts
src/paratext-bible-word-list/webpack/webpack.config.web-view.ts
webpack/webpack.config.base.ts
webpack/webpack.config.main.ts
webpack/webpack.config.web-view.ts

- update from templates
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/52)

fix imports after PBR changes

---

src/paratext-bible-word-list/src/word-list.web-view.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/53)

PT-2196 handle error from useData

---

package-lock.json
src/paratext-bible-text-collection/package.json

- also `npm audit fix`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/54)

update editor v0.7.4

---

.eslintrc.cjs
README.md
src/paratext-bible-text-collection/.eslintrc.js
src/paratext-bible-text-collection/README.md
src/paratext-bible-text-collection/webpack/webpack.config.base.ts
src/paratext-bible-word-list/.eslintrc.js
src/paratext-bible-word-list/README.md
src/paratext-bible-word-list/webpack/webpack.config.base.ts
webpack/webpack.config.base.ts
webpack/webpack.util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/58)

Remove MUI

---

package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/59)

Update from templates

---

src/paratext-bible-text-collection/src/main.ts
src/paratext-bible-text-collection/src/util.ts
src/paratext-bible-text-collection/src/web-views/components/chapter-view.component.tsx
src/paratext-bible-text-collection/src/web-views/components/verse-display.component.tsx
src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx
src/paratext-bible-word-list/src/main.ts
src/paratext-bible-word-list/src/types/paratext-bible-word-list.d.ts
src/paratext-bible-word-list/src/word-list.web-view.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/56)

PT-1653: Verse ref

---

src/paratext-bible-word-list/src/main.ts
src/paratext-bible-word-list/src/word-content-viewer.component.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/61)

PT-3030: Fix two bugs in word list

---

src/paratext-bible-word-list/README.md
src/paratext-bible-word-list/assets/descriptions/description-en.md
src/paratext-bible-word-list/assets/displayData.json
src/paratext-bible-word-list/contributions/localizedStrings.json
src/paratext-bible-word-list/contributions/menus.json
src/paratext-bible-word-list/cspell.json
src/paratext-bible-word-list/src/main.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/65)

PT-3062: Move Wordlist from app menu to web view menu

---

package-lock.json
package.json
src/paratext-bible-text-collection/manifest.json
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-word-list/manifest.json
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/68)

Bump versions to 0.3.0-alpha.0

---

src/paratext-bible-word-list/contributions/localizedStrings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/71)

PT-3062 follow up: Update missed labels

---

src/paratext-bible-text-collection/src/util.ts
src/paratext-bible-text-collection/src/web-views/components/chapter-view.component.tsx
src/paratext-bible-text-collection/src/web-views/components/verse-display.component.tsx
src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/72)

PT-1599: Implemented project-level Right-to-Left from Paratext as `textDirection`

---

package-lock.json
src/paratext-bible-text-collection/src/main.ts
src/paratext-bible-word-list/src/main.ts

The main point here is adding the timeouts, but I need to add docs to get the timeouts in, too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/73)

PT-3088 Disable request timeouts for dialogs

---

package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-text-collection/src/web-views/editor-styles/_editor-overrides.scss
src/paratext-bible-text-collection/src/web-views/editor-styles/_editor.scss
src/paratext-bible-text-collection/src/web-views/editor-styles/_usj-nodes.scss

- includes security update for `prismjs` (but not expected to be an issue)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/75)

update editor v0.7.12

---

src/paratext-bible-text-collection/manifest.json
src/paratext-bible-word-list/manifest.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/80)

Change the publisher ID to match the publisher on the marketplace

---

README.md
package-lock.json
package.json
src/paratext-bible-text-collection/README.md
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-word-list/README.md
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/86)

Bumped @swc/core to 1.13.3 (update from templates)

---

package-lock.json
package.json
src/paratext-bible-text-collection/manifest.json
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-word-list/manifest.json
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/89)

Bump versions to 0.3.0

---

package-lock.json
package.json
src/paratext-bible-text-collection/manifest.json
src/paratext-bible-text-collection/package-lock.json
src/paratext-bible-text-collection/package.json
src/paratext-bible-word-list/manifest.json
src/paratext-bible-word-list/package-lock.json
src/paratext-bible-word-list/package.json
src/paratext-bible-word-list/src/main.ts
src/paratext-bible-word-list/src/word-list.web-view.tsx

This includes the cherry-pick and version bump
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paratext-bible-extensions/92)

Cherry pick 0.3.1
